### PR TITLE
Added option to pass servers URL

### PR DESCRIPTION
**Pull request by brettmarl**
Added a new option to allow client to pass in a custom URL to obtain
list of speed test servers. This is useful in the case you are hosting
your own mini speed test instance on a private server. You can run the
speed test against your own domain.

### CODE REVIEW

**Comment by ddsol** [comment]
:+1: :shipit:

**Comment by brettmarl** [comment]
Thanks! And thanks for writing the library. 

Sent from Outlook




On Thu, Oct 8, 2015 at 7:22 PM -0700, "Han de Boer" <notifications@github.com> wrote:












Merged #15.

**Comment by brettmarl** [comment]
Han - quick question. I'm pretty new to node... so I wanted to get that
change I made via "npm install speedtest-net" but it installs and older
version. Do I need to bump the version number in package.json in order to
get this to work? I didn't touch that file.

Cheers,
-Brett

**Comment by ddsol** [comment]
Well, Brett, I have to do npm publish or something like that. Since I'm the owner of the package I have to do that. Or I could just give you the password.

But thanks for pointing that out because I haven't kept an eye on it.

**Pull request merged**
