### PR TITLE
Tidy documentation

### PR DESCRIPTION
**Pull request by jsejcksn**
See #79

### CODE REVIEW

**Comment by ddsol** [comment]
Spelling of 'module' needs fixing. Also, if you don't mind, instead of
```md
**`name`**_`: type`_
```
I think maybe
```md
**`name`**: _`type`_
```
is easier to read and I'd appreciate if you could add think if possible perchance.

Besides that, this whole module could use some rewriting from scratch. :grinning:

**Comment by jsejcksn** [comment]
Done. Great catch on the spelling—thanks! 😅

**Comment by ddsol** [comment]
Yes, there are 2 spaces between the `-` and the `**`client`**:` so that's probably the issue.

**Comment by jsejcksn** [comment]
Should be all sorted now.

**Pull request merged**
